version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: "redis:alpine"
volumes:
  dbdata: