version: "3.9"
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - WEBPACKER_DEV_SERVER_HOST=mybusiness_webpacker_1
  
  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    ports:
      - '3035:3035'
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: "redis:alpine"
volumes:
  dbdata: