version: "3.9"
services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: postgres
volumes:
  dbdata: