development:
  adapter: postgresql
  encoding: unicode
  database: mybusiness
  pool: 5
  username: postgres
  password: postgres
  host: 127.0.0.1
  port: 5432
      
test:
  adapter: postgresql
  encoding: unicode
  database: mybusiness
  pool: 5
  username: postgres
  password: postgres
  host: 127.0.0.1
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: mybusiness
  pool: 5
  username: postgres
  password: postgres
  host: 127.0.0.1
  port: 5432
