name: Deploy to staging

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bitesitestaging"
          heroku_email: "jack@thejackwu.com"
      - name: Ensure User is Still Logged in to Heroku
        run: heroku auth:whoami

      - name: Run Database Migrations
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku run rake db:migrate -a ${{secrets.HEROKU_STAGING_APP_NAME}}
